#!/usr/bin/env bash
set -e
  apt-get update
echo "Installing git command line tools"

  apt-get -qy install git
  echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  apt-get install -y ruby-full
  apt-get install -y build-essential openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison subversion
  gem install -y bundler
  cd /vagrant
echo "Installing from Gemfile"
  bundle install
